"""MathMark - 多层抗AI去水印工具，专为数学教学内容版权保护设计"""

__version__ = "0.1.0"
__author__ = "MathMark Project"

from .core.config import (
    create_default_config,
    load_config,
    load_signature,
    save_config,
    save_signature,
)
from .core.pipeline import WatermarkPipeline
from .core.types import (
    BenchmarkResult,
    C2PASettings,
    ContentType,
    CoxSettings,
    DWTSettings,
    Evidence,
    ExampleSignature,
    LayerReport,
    LayerType,
    MathSignature,
    MetadataSettings,
    SemanticSettings,
    SignerInfo,
    SignatureProblem,
    StepSignature,
    SymbolSignature,
    TrustMarkSettings,
    Verdict,
    VerificationResult,
    VisibleSettings,
    VisualSignature,
    WatermarkConfig,
    WatermarkResult,
)

__all__ = [
    "BenchmarkResult",
    "C2PASettings",
    "ContentType",
    "CoxSettings",
    "DWTSettings",
    "Evidence",
    "ExampleSignature",
    "LayerReport",
    "LayerType",
    "MathSignature",
    "MetadataSettings",
    "SemanticSettings",
    "SignerInfo",
    "SignatureProblem",
    "StepSignature",
    "SymbolSignature",
    "TrustMarkSettings",
    "Verdict",
    "VerificationResult",
    "VisibleSettings",
    "VisualSignature",
    "WatermarkConfig",
    "WatermarkPipeline",
    "WatermarkResult",
    "__version__",
    "__author__",
    "create_default_config",
    "load_config",
    "load_signature",
    "save_config",
    "save_signature",
]
